# 基于镜像alpine
FROM arm32v7/alpine:3.12

# 维护者
LABEL maintainer="Niuren.Zhu <niuren.zhu@icloud.com>"

# 安装环境
RUN set -x \
    # 安装工具
    && apk add --no-cache busybox-extras curl wget \
    openssh unrar unzip aria2 \
    # 安装FileBrowser依赖
    ca-certificates mailcap \
    # 删除源
    && rm -rf /var/cache/apk/* \
    && rm -rf /tmp/*.apk

# 安装FileBrowser
ARG FB_VERSION=v2.22.4
RUN set -x \
    # 下载文件
    && curl -sL https://github.com/filebrowser/filebrowser/releases/download/${FB_VERSION}/linux-armv7-filebrowser.tar.gz -O \
    # 解压安装
    && mkdir -p /usr/share/filebrowser \
    && tar zxvf linux-armv7-filebrowser.tar.gz -C /usr/share/filebrowser \
    && ln -s /usr/share/filebrowser/filebrowser /usr/bin/filebrowser \
    # 删除文件
    && rm -rf linux-armv7-filebrowser.tar.gz

# 安装Gost
ARG GOST_VERSION=2.11.3
RUN set -x \
    # 下载文件
    && curl -sL https://github.com/ginuerzh/gost/releases/download/v${GOST_VERSION}/gost-linux-armv7-${GOST_VERSION}.gz -O \
    # 解压安装
    && mkdir -p /usr/share/gost \
    && gunzip gost-linux-armv7-${GOST_VERSION}.gz \
    && mv gost-linux-armv7-${GOST_VERSION} /usr/share/gost/ \
    && chmod +x /usr/share/gost/gost-linux-armv7-${GOST_VERSION} \
    && ln -s /usr/share/gost/gost-linux-armv7-${GOST_VERSION} /usr/bin/gost

# 初始化脚本
COPY entrypoint.sh /entrypoint.sh
RUN ["chmod", "+x", "/entrypoint.sh"]
ENTRYPOINT ["/entrypoint.sh"]

# 暴露端口
EXPOSE 80 8080 8433 8338
