# 基于镜像ubuntu
FROM accetto/ubuntu-vnc-xfce-firefox-g3:20.04

# 切换root用户
USER 0

# 安装常用软件
RUN set -x \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    curl \
    ttf-wqy-microhei \
    scim-pinyin scim-im-agent scim-gtk-immodule \
    # 删除源
    && apt-get autoremove -y \
    && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/*

# 配置输入法
RUN \
    echo     '# SCIM'                             >/etc/profile.d/scim.sh \
    && echo  'export XMODIFIERS="@im=SCIM"'       >>/etc/profile.d/scim.sh \
    && echo  'export GTK_IM_MODULE="scim"'        >>/etc/profile.d/scim.sh \
    && echo  'export XIM_PROGRAM="scim -d"'       >>/etc/profile.d/scim.sh \
    && echo  'export QT_IM_MODULE="scim"'         >>/etc/profile.d/scim.sh \
    && echo  'scim -d'                            >>/etc/profile.d/scim.sh

# 调整参数
ENV \
    NOVNC_PORT="80" \
    VNC_PORT="8080"

# 输出VNC/noVNC配置
RUN \
    echo     "# VNC/noVNC"                             >${HOME}/.vnc_override.rc \
    && echo  "export NOVNC_PORT=${NOVNC_PORT}"         >>${HOME}/.vnc_override.rc \
    && echo  "export VNC_PORT=${VNC_PORT}"             >>${HOME}/.vnc_override.rc

EXPOSE ${VNC_PORT} ${NOVNC_PORT}

# 修改文件所属
RUN chown -R 0 "${HOME}"